import { Project, Task, Recommendation } from '../types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-spawn',
    name: 'Spawn',
    iconType: 'terminal',
    description: 'Python CLI / Developer Tool',
    stack: ['Python', 'Backend'],
    totalTasks: 6,
    activeTasks: 2,
    progressPercent: 80,
  },
  {
    id: 'proj-ucdp',
    name: 'UCDP',
    iconType: 'database',
    description: 'Data Engineering Platform',
    stack: ['Python', 'Data Pipeline'],
    totalTasks: 12,
    activeTasks: 5,
    progressPercent: 50,
  },
  {
    id: 'proj-preflight',
    name: 'Preflight',
    iconType: 'cloud',
    description: 'API Platform',
    stack: ['Go', 'API Gateway'],
    totalTasks: 8,
    activeTasks: 3,
    progressPercent: 38,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-auth-tests',
    title: 'Finish authentication tests',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: false,
    scheduledTime: '11:30',
    dueDate: 'Due tomorrow',
    estimatedMinutes: 35,
    priority: 'high',
    subtasks: [
      { id: 'sub-1', title: 'Login tests', completed: false },
      { id: 'sub-2', title: 'Token validation', completed: false },
      { id: 'sub-3', title: 'Error cases', completed: false },
    ],
  },
  {
    id: 'task-db-setup',
    title: 'Database setup',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: true,
    completedAt: '09:20',
    scheduledTime: '09:20',
    dueDate: 'Today',
    estimatedMinutes: 45,
    priority: 'high',
  },
  {
    id: 'task-api-routes',
    title: 'API routes',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: true,
    completedAt: '10:15',
    scheduledTime: '10:15',
    dueDate: 'Today',
    estimatedMinutes: 30,
    priority: 'medium',
  },
  {
    id: 'task-readme',
    title: 'README',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: false,
    scheduledTime: '14:00',
    dueDate: 'Today',
    estimatedMinutes: 25,
    priority: 'medium',
  },
  {
    id: 'task-templates',
    title: 'Implement project templates',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: false,
    scheduledTime: '15:30',
    dueDate: 'Today',
    estimatedMinutes: 50,
    priority: 'high',
  },
  {
    id: 'task-importer',
    title: 'Add structure importer',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: false,
    dueDate: 'Today',
    estimatedMinutes: 40,
    priority: 'medium',
  },
  {
    id: 'task-dep-handling',
    title: 'Fix dependency handling',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: false,
    dueDate: 'Tomorrow',
    estimatedMinutes: 35,
    priority: 'high',
  },
  {
    id: 'task-git-init',
    title: 'Git initialization',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: true,
    completedAt: 'Sep 15',
    dueDate: 'Sep 15',
    estimatedMinutes: 15,
    priority: 'low',
  },
  {
    id: 'task-readme-gen',
    title: 'README generation',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: true,
    completedAt: 'Sep 14',
    dueDate: 'Sep 14',
    estimatedMinutes: 20,
    priority: 'medium',
  },
  {
    id: 'task-venv',
    title: 'Setup virtual environment',
    projectId: 'proj-spawn',
    projectName: 'Spawn',
    completed: true,
    completedAt: 'Sep 13',
    dueDate: 'Sep 13',
    estimatedMinutes: 15,
    priority: 'low',
  },
];

export const INITIAL_RECOMMENDATION: Recommendation = {
  taskId: 'task-auth-tests',
  title: 'Finish authentication tests',
  projectName: 'Spawn',
  estimatedMinutes: 35,
  dueDateLabel: 'Due tomorrow',
  priorityLabel: 'High priority',
  reasonBullets: [
    'Due soon + high priority',
    'Fits your available time',
  ],
};
